name: GitHub Actions for checking eslint output
on: [push]
jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
    - run: npm install eslint
    - run: npm install --save eslint-config-airbnb
    - run: npm install eslint-config-airbnb-base
    - run: npm install eslint-plugin-import
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Linter
      run: make lint
      