name: GitHub Actions for checking eslint output
on: [push]
jobs:
  
  check-lint:
    runs-on: ubuntu-latest
    strategy:
        # Node versions list
        matrix:
          node-version: [14.x]
    steps: 
     - uses: actions/checkout@v2
        # Step's name
     - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        - run: make lint
      